# Generated by Django 5.1.3 on 2024-11-30 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0002_waiter_is_active_alter_waiter_joining_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tip',
            name='stripe_payment_id',
        ),
        migrations.AddField(
            model_name='tip',
            name='payment_method',
            field=models.CharField(choices=[('CARD', 'Card'), ('UPI', 'UPI')], default='CARD', max_length=20),
        ),
        migrations.AddField(
            model_name='tip',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed')], default='PENDING', max_length=10),
        ),
        migrations.AddField(
            model_name='tip',
            name='reference_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='tip',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='tip',
            name='bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant_app.bill'),
        ),
    ]
