# Generated by Django 5.1.3 on 2024-11-30 09:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0003_remove_tip_stripe_payment_id_tip_payment_method_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('waiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='restaurant_app.waiter')),
            ],
        ),
    ]
