# Generated by Django 4.2 on 2024-12-17 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0006_waiterreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='payment_method',
            field=models.CharField(choices=[('CARD', 'Card'), ('UPI', 'UPI'), ('CASH', 'Cash')], default='CASH', max_length=20),
        ),
    ]
