# Generated by Django 4.2 on 2024-12-17 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0008_alter_waiterreview_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waiterreview',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
